image: "git-community.cs.odu.edu/ryan/personal-web-page:latest" # Custom Ruby image, replace with whatever you want
stages:
  - deploy

variables:
  AWS_DEFAULT_REGION: us-east-1 # The region of our S3 bucket
  BUCKET_NAME: bageltechnologies.com         # Your bucket name

cache:
  paths:
    - vendor

deploys3-master:
  image: "python:latest"  # We use python because there is a well-working AWS Sdk
  stage: deploy
  only:
    - master@ryan/personal-web-page
  before_script:
    - pip install awscli # Install the SDK
  script:
    - rm -rf .git .gitlab-ci.yml
    - aws s3 sync /ryan/personal-web-page s3://${BUCKET_NAME}/  # Replace example-bucket with your bucket
  environment:
    name: ${CI_COMMIT_REF_SLUG}
    url: http://${BUCKET_NAME}.s3-website.${AWS_DEFAULT_REGION}.amazonaws.com/  # This is the url of the bucket we saved before
    
deploys3-dev:
  image: "python:latest"  # We use python because there is a well-working AWS Sdk
  stage: deploy
  only:
    - development@ryan/personal-web-page
  before_script:
    - pip install awscli # Install the SDK
  script:
    - rm -rf .git .gitlab-ci.yml
    - aws s3 sync /ryan/personal-web-page s3://${BUCKET_NAME}/dev  # Replace example-bucket with your bucket
  environment:
    name: ${CI_COMMIT_REF_SLUG}
    url: http://${BUCKET_NAME}.s3-website.${AWS_DEFAULT_REGION}.amazonaws.com/  # This is the url of the bucket we saved before

